# Generated by Django 4.1.7 on 2023-03-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_ID', models.CharField(default='', max_length=20)),
                ('Item_Code', models.CharField(default='', max_length=20)),
                ('Model_Name', models.CharField(default='', max_length=100)),
                ('Poorvika_Price', models.CharField(default='', max_length=20)),
                ('Flipkart_Price', models.CharField(default='', max_length=20)),
                ('Amazon_Price', models.CharField(default='', max_length=20)),
                ('Croma_price', models.CharField(default='', max_length=20)),
                ('Vijay_Price', models.CharField(default='', max_length=20)),
                ('Reliance_Price', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Home_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_ID', models.CharField(default='', max_length=20)),
                ('Item_Code', models.CharField(default='', max_length=20)),
                ('Model_Name', models.CharField(default='', max_length=100)),
                ('Poorvika_Price', models.CharField(default='', max_length=20)),
                ('Flipkart_Price', models.CharField(default='', max_length=20)),
                ('Amazon_Price', models.CharField(default='', max_length=20)),
                ('Croma_price', models.CharField(default='', max_length=20)),
                ('Vijay_Price', models.CharField(default='', max_length=20)),
                ('Reliance_Price', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_ID', models.CharField(default='', max_length=20)),
                ('Item_Code', models.CharField(default='', max_length=20)),
                ('Model_Name', models.CharField(default='', max_length=100)),
                ('Poorvika_Price', models.CharField(default='', max_length=20)),
                ('Flipkart_Price', models.CharField(default='', max_length=20)),
                ('Amazon_Price', models.CharField(default='', max_length=20)),
                ('Croma_price', models.CharField(default='', max_length=20)),
                ('Vijay_Price', models.CharField(default='', max_length=20)),
                ('Reliance_Price', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mobiles_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_ID', models.CharField(default='', max_length=20)),
                ('Item_Code', models.CharField(default='', max_length=20)),
                ('Model_Name', models.CharField(default='', max_length=100)),
                ('Poorvika_Price', models.CharField(default='', max_length=20)),
                ('Flipkart_Price', models.CharField(default='', max_length=20)),
                ('Amazon_Price', models.CharField(default='', max_length=20)),
                ('Croma_price', models.CharField(default='', max_length=20)),
                ('Vijay_Price', models.CharField(default='', max_length=20)),
                ('Reliance_Price', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tablets_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_ID', models.CharField(default='', max_length=20)),
                ('Item_Code', models.CharField(default='', max_length=20)),
                ('Model_Name', models.CharField(default='', max_length=100)),
                ('Poorvika_Price', models.CharField(default='', max_length=20)),
                ('Flipkart_Price', models.CharField(default='', max_length=20)),
                ('Amazon_Price', models.CharField(default='', max_length=20)),
                ('Croma_price', models.CharField(default='', max_length=20)),
                ('Vijay_Price', models.CharField(default='', max_length=20)),
                ('Reliance_Price', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tv_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_ID', models.CharField(default='', max_length=20)),
                ('Item_Code', models.CharField(default='', max_length=20)),
                ('Model_Name', models.CharField(default='', max_length=100)),
                ('Poorvika_Price', models.CharField(default='', max_length=20)),
                ('Flipkart_Price', models.CharField(default='', max_length=20)),
                ('Amazon_Price', models.CharField(default='', max_length=20)),
                ('Croma_Price', models.CharField(default='', max_length=20)),
                ('Vijay_Price', models.CharField(default='', max_length=20)),
                ('Reliance_Price', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='kitchen_model',
            name='Croma_price',
        ),
        migrations.AlterField(
            model_name='kitchen_model',
            name='Amazon_Price',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='kitchen_model',
            name='Flipkart_Price',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='kitchen_model',
            name='Item_Code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='kitchen_model',
            name='Poorvika_Price',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='kitchen_model',
            name='Product_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='kitchen_model',
            name='Reliance_Price',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='kitchen_model',
            name='Vijay_Price',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='kitchen_model',
            name='Croma_Price',
            field=models.CharField(default='', max_length=20),
        ),
    ]
