# Generated by Django 4.1.7 on 2023-03-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_db', '0002_access_models_home_models_laptop_models_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Access_models',
            new_name='Access_model',
        ),
        migrations.RenameModel(
            old_name='Tablets_models',
            new_name='Home_model',
        ),
        migrations.RenameModel(
            old_name='Mobiles_models',
            new_name='Laptop_model',
        ),
        migrations.RenameModel(
            old_name='Home_models',
            new_name='Mobiles_model',
        ),
        migrations.RenameModel(
            old_name='Laptop_models',
            new_name='Tablets_model',
        ),
    ]
