# Generated by Django 4.1.7 on 2023-03-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_db', '0004_delete_home_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchen_model',
            old_name='flipkart_Price',
            new_name='flipkart_price',
        ),
    ]
