# Generated by Django 4.1.7 on 2023-03-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_db', '0005_rename_flipkart_price_kitchen_model_flipkart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', max_length=20)),
                ('item_code', models.CharField(default='', max_length=20)),
                ('model_name', models.CharField(default='', max_length=100)),
                ('poorvika_price', models.CharField(default='', max_length=20)),
                ('flipkart_price', models.CharField(default='', max_length=20)),
                ('sathiya_price', models.CharField(default='', max_length=20)),
                ('viveks_price', models.CharField(default='', max_length=20)),
                ('amazon_price', models.CharField(default='', max_length=20)),
                ('croma_price', models.CharField(default='', max_length=20)),
                ('vijay_price', models.CharField(default='', max_length=20)),
                ('reliance_price', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='access_model',
            old_name='flipkart_Price',
            new_name='flipkart_price',
        ),
        migrations.RenameField(
            model_name='laptop_model',
            old_name='flipkart_Price',
            new_name='flipkart_price',
        ),
        migrations.RenameField(
            model_name='mobiles_model',
            old_name='flipkart_Price',
            new_name='flipkart_price',
        ),
        migrations.RenameField(
            model_name='tablets_model',
            old_name='flipkart_Price',
            new_name='flipkart_price',
        ),
        migrations.RenameField(
            model_name='tv_model',
            old_name='flipkart_Price',
            new_name='flipkart_price',
        ),
    ]
