# Generated by Django 4.1.7 on 2023-03-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_db', '0006_home_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_model',
            old_name='vijay_price',
            new_name='darling_price',
        ),
        migrations.AddField(
            model_name='home_model',
            name='vasanth_price',
            field=models.CharField(default='', max_length=20),
        ),
    ]
